apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fjvoph966-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fjvoph966-nodejs 
  name: fjvoph966-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fjvoph966-nodejs 
